### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by Neuroforge** [adishavit/party_parrot#2]
What you are doing here is great. I would really like to turn my C++ code using OpenCV directly into Javascript without having to write my code in Javascript using OpenCVjs.

Can you please provide build instructions?

Your blog mentions how to build OpenCV with emscripten with Ninja. However, you only mention that there is a cmake file for Party Parrot. There is not instructions on how to ensure building it correctly.

> "For the impatient:
> 
> On Windows 10: I built OpenCV static libs with CMake, the ninja generator and the Emscripten toolchain.
> I created a new C++ OpenCV project with desktop and Emscripten targets.
> For the web target, created C wrapper functions to handle RGBA image buffers
> On the JS glue side:
> get frames from HTML5 video element;
> copy them to the Emscripten heap memory and pass to asm code;
> convert result frames to TypedArrays;
> display on HTML canvas"

How do you compile colour_cycle_js.cpp?
How is the OpenCV package that is built, cross-compiled with emscripten, linked to your final OpenCV project?

I have tried cmake, then make using the provided cmake file.

Regards,

Daniel

**Comment by adishavit** [comment]
I don't understand the problem. 
The CMakeLists.txt file is in this repo.
The [blog post](http://videocortex.io/2017/opencv-web-app/) painstakingly explains how to build.
CMake generates the build script - ninja then creates the `.js` files that the HTML loads.
What are the problems you are having?
