### ISSUE TITLE
I can't use a compiled file to draw a circle through OpenCV。

### ISSUE THREAD

**Issue by tangtao007** [adishavit/party_parrot#3]
hi I downloaded the code and wrote a simple code through Ubuntu to draw a circle, but I don't know why I can't display it successfully on the page plz help me  thanks.

this is my code:
	int EMSCRIPTEN_KEEPALIVE draw_cicle() {
	Point center = Point(255,255);
	int r = 100;
	Mat picture(500,500,CV_8UC3,Scalar(255,255,255));
	circle(picture,center,r,Scalar(0,0,0));
	imshow("imag",picture);
}

**Comment by adishavit** [comment]
You cannot use imshow() since there is no UI support in Emacripten.

**Comment by tangtao007** [comment]
@adishavit I'm really glad to see your reply. I have been waiting for your reply. If I want to draw a circle to display in the HTML, could you give me some hints? Thanks.

**Comment by adishavit** [comment]
That’s really outside the scope of this blog post.

**Comment by tangtao007** [comment]
@adishavit Ok, I'm going to close this problem and I'm going to share if I solve it. I have another problem with compilation. I will open another one about dnn. Thank you
